### ISSUE TITLE
如何动态更新资源权限？

### ISSUE THREAD

**Issue by lwhua** [tomsun28/sureness#48]
通过管理后台界面添加了资源和对应的角色授权，目前需要重启服务才能更新权限，如何动态更新资源权限？

**Comment by tomsun28** [comment]
你好不用重启，可以通过```TreePathRoleMatcher rebuildTree``` 来刷新权限树 具体操作可以参考 [sample-tom](https://github.com/tomsun28/sureness/tree/master/sample-tom) 样例的 ```@PostMapping("/authority/resource/{roleId}/{resourceId}")``` 接口实现
