### ISSUE TITLE
JWT 认证方式下  Subject 中获取不到 principal

### ISSUE THREAD

**Issue by lyy2002** [tomsun28/sureness#50]
SubjectSum subject = SurenessSecurityManager.getInstance().checkIn(servletRequest);
            Object principal = subject.getPrincipal();
            System.out.println(principal);    //  null

0.4.1版本，jwt 认证方式

**Comment by tomsun28** [comment]
感谢，我马上出个新的0.4.2版本fix

**Comment by tomsun28** [comment]
hi thanks for this, the bug has been resolved after v0.4.2, I will close it if there is nothing else
